{
 "title": "Power Monitor",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Watts",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 3, "x": 5, "y": 0 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "device" ], "type": "tag" }
     ],
     "measurement": "realpower",
     "query": "SELECT sum(\"value\") FROM \"realpower\" WHERE (\"device\" = 'rpict3v1') AND $timeFilter GROUP BY time(2s), \"device\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "rpict3v1" }
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "format": "watth",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "realpower",
     "query": "SELECT integral(\"value\") / 3600 FROM \"realpower\" WHERE (\"device\" = 'rpict3v1') AND $timeFilter GROUP BY time(2s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "rpict3v1" }
     ]
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 0 },
   "format": "watth",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "realpower",
     "query": "SELECT integral(\"value\") / 3600 FROM \"realpower\" WHERE (\"device\" = 'rpict3v1') AND $timeFilter GROUP BY time(2s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "rpict3v1" }
     ]
    }
   ]
  },
  {
   "title": "Real Power",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Watts (W)" }
   ],
   "targets": [
    {
     "alias": "Split-Phase A",
     "groupBy": [
      { "params": [ "channel" ], "type": "tag" }
     ],
     "measurement": "realpower",
     "query": "SELECT \"value\" FROM \"realpower\" WHERE (\"channel\" = '01' AND \"device\" = 'rpict3v1') AND $timeFilter GROUP BY \"channel\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "rpict3v1" },
      { "condition": "AND", "key": "channel", "operator": "=", "value": "01" }
     ]
    },
    {
     "alias": "Split-Phase B",
     "groupBy": [
      { "params": [ "channel" ], "type": "tag" }
     ],
     "measurement": "realpower",
     "query": "SELECT \"value\" FROM \"realpower\" WHERE (\"channel\" = '01' AND \"device\" = 'rpict3v1') AND $timeFilter GROUP BY \"channel\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "rpict3v1" },
      { "condition": "AND", "key": "channel", "operator": "=", "value": "02" }
     ]
    }
   ]
  },
  {
   "title": "Split-Phase A Amps",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "irms",
     "query": "SELECT last(\"value\") FROM \"irms\" WHERE (\"device\" = 'rpict3v1' AND \"channel\" = '01') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "rpict3v1" },
      { "condition": "AND", "key": "channel", "operator": "=", "value": "01" }
     ]
    }
   ]
  },
  {
   "title": "Split-Phase B Amps",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "irms",
     "query": "SELECT last(\"value\") FROM \"irms\" WHERE (\"device\" = 'rpict3v1' AND \"channel\" = '02') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "rpict3v1" },
      { "condition": "AND", "key": "channel", "operator": "=", "value": "02" }
     ]
    }
   ]
  },
  {
   "title": "Apparent Power",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Volt-Amps (VA)" }
   ],
   "targets": [
    {
     "alias": "Split-Phase A",
     "groupBy": [
      { "params": [ "channel" ], "type": "tag" }
     ],
     "measurement": "apparantpower",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "rpict3v1" },
      { "condition": "AND", "key": "channel", "operator": "=", "value": "01" }
     ]
    },
    {
     "alias": "Split-Phase B",
     "groupBy": [
      { "params": [ "channel" ], "type": "tag" }
     ],
     "measurement": "apparantpower",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "rpict3v1" },
      { "condition": "AND", "key": "channel", "operator": "=", "value": "02" }
     ]
    }
   ]
  },
  {
   "title": "Split-Phase A Volts",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 14 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "irms",
     "query": "SELECT last(\"value\") FROM \"vrms\" WHERE (\"device\" = 'rpict3v1' AND \"channel\" = '01') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "rpict3v1" },
      { "condition": "AND", "key": "channel", "operator": "=", "value": "01" }
     ]
    }
   ]
  },
  {
   "title": "Split-Phase B Volts",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 14 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "irms",
     "query": "SELECT last(\"value\") FROM \"vrms\" WHERE (\"device\" = 'rpict3v1' AND \"channel\" = '02') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "rpict3v1" },
      { "condition": "AND", "key": "channel", "operator": "=", "value": "01" }
     ]
    }
   ]
  },
  {
   "title": "Daily kWh",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Consumed Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "realpower",
     "query": "SELECT integral(\"value\") / 3600 FROM \"realpower\" WHERE (\"device\" = 'rpict3v1') AND $timeFilter GROUP BY time(2s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "rpict3v1" }
     ]
    }
   ]
  },
  {
   "title": "Monthly kWh",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Consumed Power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "realpower",
     "query": "SELECT integral(\"value\") / 3600 FROM \"realpower\" WHERE (\"device\" = 'rpict3v1') AND $timeFilter GROUP BY time(2s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "integral"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device", "operator": "=", "value": "rpict3v1" }
     ]
    }
   ]
  }
 ]
}